src/utils/styles.test.ts
=> feat: tests for style generator

package.json, src/components/Base.tsx, src/components/Root.tsx
Also deprecated the Base component
=> fix: proper order of contexts in the Root

src/components/pickers/Menu/styled.tsx
Fix of broken menu header
Missed after code review in Menu Component PR https://github.com/cube-js/cube-ui-kit/pull/58
=> fix: broken color token

src/components/pickers/Menu/Menu.tsx, src/components/pickers/Menu/MenuSection.tsx, src/components/pickers/Menu/styled.tsx
#dark-04 -> #dark-03
menu item margin -> menu item gap
=> fix: section header color and gap between items

package.json, scripts/ci/measure-size.mjs, yarn.lock
This PR reduces the size of node_modules by 50%(and by 400% when gzipped) by deduping and removing unused dependencies
=> Reduce deps size by 50%

.changeset/smart-wasps-wink.md, src/components/pickers/Menu/MenuItem.tsx, src/components/pickers/Menu/MenuSection.tsx, src/components/pickers/Menu/styled.tsx
Section header from C1 to C2 also adds bg to section header
=> fix(Menu): Section Header

.changeset/sour-planes-talk.md, src/components/forms/FieldWrapper.tsx, src/components/forms/Form/Field.stories.tsx, src/components/forms/Form/Field.tsx, src/index.ts
Field: pass styles prop
Field: add stories
index: export CubeRadioGroupProps type
=> fix(Field): pass styles

.changeset/early-donuts-appear.md, src/tasty/styles/gap.ts
Fix the `display` style default value in `gap` style generator.
=> fix(gap): display default value

.changeset/neat-bikes-wonder.md, src/components/content/Card/Card.tsx, src/tasty/__snapshots__/tasty.test.tsx.snap, src/tasty/tasty.test.tsx
=> fix(Card): pass style props

src/components/overlays/Dialog/stories/DialogForm.stories.tsx
Add `DialogContainer` example for DialogForm.
=> test(DialogForm): add container example

.changeset/serious-mails-remember.md, src/components/layout/Space.tsx
Fix condition for the vertical modifier in `Space` component.
=> fix(Space): vertical modifier

.changeset/six-parrots-bathe.md, src/components/forms/Form/Field.stories.tsx, src/components/forms/Form/Field.tsx
fix(Field): pass labelPosition prop
=> fix(Field): pass labelPosition prop

.changeset/clean-swans-grin.md, src/components/forms/Form/Field.stories.tsx, src/components/forms/Form/Field.tsx
fix(Field): pass labelStyles prop
=> fix(Field): pass labelStyles prop

.changeset/violet-flowers-remain.md, src/components/forms/Checkbox/Checkbox.tsx, src/components/forms/FieldWrapper.tsx, src/components/forms/Label.tsx, src/components/forms/RadioGroup/RadioGroup.tsx, src/components/forms/Switch/Switch.tsx, src/tasty/tasty.test.tsx, src/tasty/utils/styles.test.ts, src/tasty/utils/styles.ts
Fix extractStyles() logic.
Fix label position inside a field.
=> fix: extractStyles() logic fix & field label position fix

.changeset/chilly-dots-tell.md, src/components/layout/Space.tsx, src/components/pickers/Menu/Menu.stories.tsx, src/stories/Typography.stories.mdx
=> fix(Space): items alignment

src/components/forms/Form/Field.tsx, src/components/organisms/FileTabs/FileTabs.tsx
=> fix(FileTabs): styles

.changeset/few-rice-worry.md, package.json, yarn.lock
Hotfix for ComboBox. (updates to react-stately)
=> fix(Combobox): error on trigger

.changeset/little-months-share.md, src/components/overlays/NewNotifications/Bar/NotificationsBar.tsx
=> fix: zIndex of the bar

.changeset/dry-jars-train.md, src/components/actions/Button/Button.stories.tsx, src/components/actions/Button/Button.tsx
=> Fix icon button sizes

.changeset/wise-ducks-rest.md, src/components/forms/Switch/Switch.tsx
Fix styles for Switch in the disabled state.
=> fix(Switch): thumb disabled styles

.changeset/nine-dolls-warn.md, src/components/overlays/NewNotifications/Bar/NotificationsBar.tsx, src/components/overlays/NewNotifications/NotificationView/NotificationAction.tsx, src/components/overlays/NewNotifications/NotificationView/NotificationDescription.tsx, src/components/overlays/NewNotifications/NotificationView/NotificationFooter.tsx, src/components/overlays/NewNotifications/NotificationView/NotificationHeader.tsx, src/components/overlays/NewNotifications/Notifications.stories.tsx, src/components/overlays/NewNotifications/NotificationsContext/use-notifications.ts, src/components/overlays/NewNotifications/NotificationsList.tsx, src/components/overlays/Toasts/toast.test.tsx, src/components/overlays/Toasts/use-toasts-api.ts
=> MIsc bugfixes in Notifications

.changeset/modern-eagles-perform.md, src/components/pickers/Menu/Menu.stories.tsx, src/components/pickers/Menu/MenuItem.tsx
=> fix: add customization form Menu.Item

.changeset/short-zebras-brake.md, src/components/overlays/Tooltip/Tooltip.stories.tsx, src/components/overlays/Tooltip/TooltipProvider.tsx
=> fix(TooltipProvider): childrenchildrenchildren bug

src/components/actions/Button/Button.stories.tsx, src/components/actions/Button/Button.tsx, src/components/overlays/Dialog/Dialog.tsx, src/components/pickers/Menu/MenuButton.tsx, src/stories/Result.stories.mdx
Button component:
Add fixed sizes for icons.
Add `rightIcon` prop.
Migrate `default` type to `secondary`.
Migrate `default` size to `medium`.
=> feat(Button): add sizes for icons and rightIcon prop

.changeset/bright-pens-sneeze.md, src/_internal/hooks/use-sync-ref.ts, src/components/forms/TextArea/TextArea.tsx, src/components/navigation/LegacyTabs/LegacyTabs.tsx, src/components/organisms/FileTabs/FileTabs.tsx, src/components/overlays/AlertDialog/AlertDialog.tsx, src/components/overlays/NewNotifications/Notification.tsx, src/components/overlays/NewNotifications/NotificationView/NotificationView.tsx, src/components/overlays/Toasts/Toast.tsx, src/components/pickers/ComboBox/ComboBox.tsx, src/components/pickers/Menu/Menu.tsx, src/utils/react/mergeProps.tsx
I had to add a changelog for other PR here 'cause I forgot to add it there. ^^'
=> fix: utils migration and more

.changeset/eleven-geckos-protect.md, src/components/actions/Button/Button.tsx, src/components/actions/Button/button.test.tsx
=> Various bugfixes after 0.12

src/components/forms/Checkbox/Checkbox.tsx, src/components/forms/Checkbox/CheckboxGroup.tsx, src/components/forms/FileInput/FileInput.tsx, src/components/forms/RadioGroup/Radio.tsx, src/components/forms/RadioGroup/RadioGroup.stories.tsx, src/components/forms/RadioGroup/RadioGroup.tsx, src/components/forms/Switch/Switch.tsx, src/components/forms/TextInput/TextInputBase.tsx, src/components/pickers/ComboBox/ComboBox.tsx, src/components/pickers/Select/Select.tsx, src/shared/form.ts
=> Pass labelSuffix in form components

.changeset/green-berries-fold.md, src/components/actions/Button/Button.tsx, src/components/forms/Checkbox/Checkbox.stories.tsx, src/components/forms/Checkbox/CheckboxGroup.stories.tsx, src/components/forms/FileInput/FileInput.tsx, src/components/forms/Label.tsx, src/components/forms/NumberInput/StepButton.tsx, src/components/forms/PasswordInput/PasswordInput.tsx, src/components/forms/RadioGroup/RadioGroup.stories.tsx, src/components/forms/SearchInput/SearchInput.stories.tsx, src/components/forms/SearchInput/SearchInput.tsx, src/components/forms/TextArea/TextArea.stories.tsx, src/components/forms/TextInput/TextInput.stories.tsx, src/components/forms/TextInput/TextInputBase.tsx, src/components/pickers/ComboBox/ComboBox.stories.tsx, src/components/pickers/ComboBox/ComboBox.tsx, src/components/pickers/Select/Select.stories.tsx, src/components/pickers/Select/Select.tsx, src/stories/FormFieldArgs.ts
TextInputBase
- prefix/suffix refactoring with grid layout
- add `icon` property
=> fix(TextInputBase): additionals refactoring

.changeset/silent-weeks-deliver.md, src/components/forms/Form/Form.tsx, src/components/forms/Form/useForm.tsx
=> Fix types in Form

.changeset/shaggy-apricots-care.md, src/components/forms/FieldWrapper.tsx
=> Reduce gap betwel label and labelSuffix

src/components/overlays/NewNotifications/Bar/NotificationsBar.tsx, src/components/overlays/NewNotifications/Notifications.stories.tsx
=> Fix: increase zIndex of Notifications bar

.changeset/late-melons-remain.md, src/components/forms/Form/Form.tsx
=> Fix: form callback types

.changeset/tough-tips-hear.md, src/components/navigation/LegacyTabs/LegacyTabs.tsx, src/components/organisms/FileTabs/FileTabs.tsx
=> fix(LegacyTabs): fade z-index

.changeset/five-walls-beam.md, src/components/forms/NumberInput/NumberInput.stories.tsx, src/components/forms/NumberInput/NumberInput.tsx, src/components/forms/NumberInput/StepButton.tsx
Fixes the small size of the NumberInput.
=> fix(NumberInput): small size

src/components/overlays/OverlayWrapper.tsx, src/stories/Layout.stories.mdx, src/stories/Styles.stories.mdx, src/tasty/providers/BreakpointsProvider.tsx
- Update documentation and add Layout stories.
- Minor typings updates.
=> fix: documentation and typings

.changeset/unlucky-chicken-greet.md, .github/workflows/main.yml, .github/workflows/pull-request.yml, .storybook/main.js
This PR improves SWC configuration and speeds up both dev and prod build time by 30-50%.
---
---
Closes:  N/A 
#
N/A
=> chore: Improve SWC configuration

.changeset/eleven-kangaroos-talk.md, src/components/overlays/Tooltip/Tooltip.tsx, src/components/pickers/Menu/Menu.stories.tsx, src/components/pickers/Menu/Menu.tsx, src/components/pickers/Menu/MenuSection.tsx
Fixes `wrapper` prop support on Menu Item.
Fixes styles of Tooltip's Tip to better match the geometry of a tooltip.
=> fix(Menu): wrapper support

.changeset/thick-suns-cross.md, src/components/forms/Label.tsx, src/components/forms/RadioGroup/Radio.tsx, src/components/forms/RadioGroup/RadioGroup.stories.tsx, src/components/forms/RadioGroup/RadioGroup.tsx
Reduce the distance between radio buttons inside Radio.Group
=> fix(RadioGroup): gap for radio buttons

.changeset/famous-bananas-rest.md, src/components/forms/Checkbox/Checkbox.tsx, src/components/forms/Checkbox/CheckboxGroup.tsx, src/components/forms/FieldWrapper.tsx, src/components/forms/Form/ComplexForm.stories.tsx, src/components/forms/Form/Field.tsx, src/components/forms/Form/Form.tsx, src/components/forms/RadioGroup/RadioGroup.tsx, src/components/forms/RangeSlider/RangeInput.tsx, src/components/forms/RangeSlider/RangeSlider.tsx, src/components/forms/RangeSlider/styled.ts, src/components/forms/Switch/Switch.tsx, src/stories/Form.stories.mdx, src/tasty/tasty.tsx
=> feat(Form): horizontal layout support

.changeset/strong-hotels-compare.md, src/components/forms/Checkbox/Checkbox.tsx, src/components/forms/Checkbox/CheckboxGroup.tsx, src/components/forms/Checkbox/checkbox-group.test.tsx, src/components/forms/Checkbox/checkbox.test.tsx, src/components/forms/Form/field.test.tsx, src/components/forms/Form/index.ts, src/components/forms/Form/use-field/use-field-props.tsx, src/components/forms/Form/use-field/use-field.ts, src/components/forms/NumberInput/NumberInput.tsx, src/components/forms/PasswordInput/PasswordInput.tsx, src/components/forms/PasswordInput/password-input.test.tsx, src/components/forms/RadioGroup/Radio.tsx, src/components/forms/RadioGroup/RadioGroup.tsx, src/components/forms/RadioGroup/radio.test.tsx, src/components/forms/Slider/Slider.tsx, src/components/forms/Slider/SliderBase.tsx, src/components/forms/Slider/types.ts, src/components/forms/Switch/Switch.tsx, src/components/forms/Switch/switch.test.tsx, src/components/forms/TextArea/TextArea.tsx, src/components/forms/TextArea/textarea.test.tsx, src/components/forms/TextInput/TextInput.tsx, src/components/forms/TextInput/TextInputBase.tsx, src/components/forms/TextInput/text-input.test.tsx, src/components/pickers/ComboBox/ComboBox.tsx, src/components/pickers/ComboBox/combobox.test.tsx, src/components/pickers/Select/Select.tsx, src/components/pickers/Select/select.test.tsx
=> [CUK-5] Field migration step 2

.changeset/large-garlics-clean.md, src/components/Root.tsx, src/provider.tsx, src/utils/react/useViewportSize.ts
=> Fix Rerenders on resize

.changeset/smooth-shoes-impress.md, .changeset/tall-paws-perform.md, src/components/pickers/ComboBox/ComboBox.tsx, src/components/pickers/ComboBox/combobox.test.tsx
=> Fix types in Combobox and fix filter function

.changeset/honest-fireants-destroy.md, src/components/form/FieldWrapper/FieldWrapper.tsx
=> fix(Field): label suffix gap

.changeset/brave-chefs-dance.md, .changeset/silver-pans-shake.md, src/components/fields/TextArea/TextArea.stories.tsx, src/components/fields/TextArea/TextArea.tsx
=> feat: max visible rows option to autosizing textarea
